language: php
php:
  - 5.4
before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
  - mysql -e 'CREATE DATABASE bluz;'
  - mysql -e 'USE bluz; SET foreign_key_checks = 0; SOURCE structure.ddl; SET foreign_key_checks = 1;'
  - mysql -uroot bluz < dump.sql
script: phpunit --configuration tests/phpunit.xml --coverage-text