language: php
php:
  - 5.4
before_script:
  # Composer
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
  - mysql -uroot bluz < structure.ddl
  - mysql -uroot bluz < dump.sql
script:
  # Unit Tests
  - phpunit --configuration tests/phpunit.xml --coverage-text
